name: Web Scraping and Save to JSON

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  scrape_and_save:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: pull
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull

      - name: Install dependencies
        run: |
        pip install urllib3
        pip install bs4
        pip install google-api-python-client

      - name: Run Python script
        run: python scrape_and_save.py

      - name: Commit and push changes
        run: |
          git add data.json
          git commit -m "Update HTML data (auto)"
          git push
